//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using BuiltBroken.Damage;
using BuiltBroken;

namespace BuiltBroken.TurnBased.Entity
{
	public class EntityLiving: EntityBase
	{
		protected float health = 0;
		protected float maxHealth = 10;

		protected EntityBase lastAttacker;
		protected EntityBase currentTarget;

		public EntityLiving (GameBoard board): base(board)
		{
			this.health = getMaxHealth();
		}		

		/** Called by the attacking entity to damage this
		 *  entity
		 *  @param attacker - entity that caused the damage
		 *  @param damage - amount to cause harm by
		 */
		public void takeDamage(EntityBase attacker, DamageSource source, float damage)
		{
			lastAttacker = attacker;
			health -= damage;
		}

		public float getHealth()
		{
			return health;
		}

		public float getMaxHealth()
		{
			return maxHealth;
		}
	}		
}

